# fly.toml file generated for aes-crypto-util-web on 2023-06-21T21:48:40+09:00

app = "aes-crypto-util-web"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
